### ISSUE TITLE
Loading table columns other than String and Double

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/cytoscape-automation#11]
Currently, I can only load Strings and Doubles, relying on Cytoscape to guess which of the two I am importing. For example, if I send integers... they go into a Double column.  Ideally, I could specify the format to override this default behavior

**Comment by AlexanderPico** [comment]
Possible solution might be to specify format as a parameter in either the wrapper function or the CyREST operation... need to consider options.

https://github.com/cytoscape/cytoscape-automation/blob/master/for-scripters/R/r2cytoscape/R/loadTableData.R

**Comment by dotasek** [comment]
There's a way to get the results you want.

You need to define the column prior to loading data into it.

First, use a POST to ```http://localhost:1234/v1/networks/52/tables/defaultnode/columns``` using a message body to define the column:

```
{
  "name": "exp1",
  "type": "Integer",
  "immutable": false,
  "list": false,
  "local": false
}
```

Then, you can load column data with what I assume was your original operation, PUT http://localhost:1234/v1/networks/52/tables/defaultnode/ with a message body containing data (my network had an SUID 62; you'll have to adapt this to your network):

```
{
  "key":"SUID",
  "dataKey": "id",
  "data": [
    {
      "id": 62,
      "exp1": 1,
      "exp2": 2
    }
  ]
}
```

Note that ```exp2``` will load to with the previous behaviour you described.

Let me know if this works.
