### ISSUE TITLE
Have to run function twice!

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/cytoscape-automation#13]
Very odd behavior.  In order to get a new visual mapping to stick, I have to run the PUT method twice. See wrapper function:

https://github.com/cytoscape/cytoscape-automation/blob/master/for-scripters/R/r2cytoscape/R/updateStyleMapping.R#L37

When you run this PUT once, you get no effect or some "odd" effect (like clearing a style mapping), then the second application fixes it. I think you can continue to get this effect with every even application fixing the effect of odd applications.  WEIRD.

**Comment by dotasek** [comment]
Seems to be a problem in CyREST itself. Moved to [this issue](https://github.com/cytoscape/cyREST/issues/26) in the CyREST repository.
