### ISSUE TITLE
Unable to select node using selectNodes with node list more than 500

### ISSUE THREAD

**Issue by risserlin** [cytoscape/cytoscape-automation#18]
running: 
response <- selectNodes(nodes = nodes_to_select,network = network, base.url = base.url)

with a matrix of 511 nodes. 
returns (after a long while) with the following error:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  URL using bad/illegal format or missing URL

stepping through the code it seems to be having issues with this line in the code:
node.list.str = paste(node.list.str,paste(by.col,n,sep=":"),sep=",")

Maybe there is a length restrictions in R or with the command?

**Comment by risserlin** [comment]
created a selection function using cyrest directly instead of commands and it runs no problem:

#' Select given nodes. Given a table that has a column called 'suids' method selects the nodes with supplied suids in
#'
  #' @param base.url cyrest base url for communicating with cytoscape
#' @param network suid or name of the network that you want to get the view for
#' @param nodes a matrix with nodes that you want to select.  The table needs to have a column with SUIDs
#' @param keep.selected (boolean) whether to add to existing selection (TRUE) or clear prior selection (FALSE); default is FALSE
#' @return server response
#' @export
#' @import RJSONIO
#' @import httr


selectNodesCyrest <- function(nodes, keep.selected=F, network="current",base.url='http://localhost:1234/v1'){

    if(class(network)=='character') # if name...
      network = getNetworkSuid(network.name=network,base.url=base.url) # then get SUID

    if (!keep.selected)
      clearSelection(network=network,base.url=base.url)

    #go through the set of nodes and create key-value pairs
      if(!is.null(nodes) && length(nodes) > 0){

            key_value_pairs <- c()
            for(k in 1:dim(nodes)[1]){
                current <- list( id = paste(nodes[k,'SUID']),selected = "true")
                key_value_pairs <- c(key_value_pairs,list(current))
              }

              selection <- list( key = "SUID", dataKey="id", data = key_value_pairs)

                selection <- toJSON(selection)

                  get.node.column.url <- paste(base.url,"networks",network,"tables/defaultnode",sep="/")

                    return(response <- PUT(url=get.node.column.url,body=selection, encode="json"))
                }
    else{
        return("nothing selected")
      }
  }

**Comment by AlexanderPico** [comment]
Finally got around to fixing this one! A number of functions have been updated to use POST where ever it is likely (possible) that parameters will be long.
