### ISSUE TITLE
Finalize Standard JSON Representations

### ISSUE THREAD

**Issue by dotasek** [cytoscape/cytoscape-automation#20]
To encourage uniformity across automation apps, a standard set of JSON representations of the Cytoscape data model should be agreed upon.

The following wiki page has been created to document current practices within CyREST and possibly improve them:

https://github.com/cytoscape/cytoscape-automation/wiki/Standard-Cytoscape-JSON-Models

All the models were taken from the org.cytoscape.model package, and any existing implementations within CyREST were added where appropriate.

When a model is agreed upon, the following checklist will be updated:

- [x]  CyColumn.java
- [x]  CyDisposable.java
- [x]  CyEdge.java
- [x]  CyIdentifiable.java
- [x]  CyNetwork.java
- [x]  CyNetworkFactory.java
- [x]  CyNetworkManager.java
- [x]  CyNetworkTableManager.java
- [x]  CyNode.java
- [x]  CyRow.java
- [x]  CyTable.java
- [x]  CyTableFactory.java
- [x]  CyTableManager.java
- [x]  CyTableMetadata.java
- [x]  CyTableUtil.java
- [x]  SavePolicy.java
- [x]  SUIDFactory.java
- [x]  VirtualColumnInfo.java

**Comment by dotasek** [comment]
There are some issues I have with the current CyREST implementations.

First and foremost, I don't like that the SUID and other 'reserved' fields are included in the data fields.

For example, this is what I don't like:

```json
{
  "data": {
    "source": 62,
    "target": 63,
    "SUID": 83,
    "shared name": "Node 2 (interacts with) Node 1",
    "shared interaction": "interacts with",
    "name": "Node 2 (interacts with) Node 1",
    "selected": false,
    "interaction": "interacts with"
  }
}
```

and this is what I'd prefer to see:

```json
{
   "SUID": 83,
   "source": 62,
   "target": 63,
   "data": {
      "shared name": "Node 2 (interacts with) Node 1",
      "shared interaction": "interacts with",
      "name": "Node 2 (interacts with) Node 1",
      "selected": false,
      "interaction": "interacts with"
    }
}
```

Since we can't break any contracts, these outputs will have to remain, however, there might be a way to version our output to provide more sound output.

**Comment by scootermorris** [comment]
Looking at the list, do we need to consider org.cytoscape.models.subnetwork in some way?

**Comment by dotasek** [comment]
Regarding my previous criticism of SUIDs in the data field, the core Toronto devs  (@chrtannus @mikekucera ) believe the original way is more representative; SUID, name, etc, appear as column data throughout the application. Based on that, I'm inclined to agree.

**Comment by dotasek** [comment]
@scootermorris I think we could get away without models.subnetwork; unless I've missed something, they could simply be represented in exchanges of SUIDs and SUID lists (so if I want the subnetworks of a network I'd get ```[203, 304, 405]```, and if I want a subnetwork's parent, I'd get a single ID.

I could see utility in something like the following:

```json
network: { 
   "SUID": 52,
   "subnetworks": [
      { "SUID": 203,
         "subnetworks": []
      }, ...
   ]
}
```

My only complaint about the above is that we might be doing more than is necessary.

**Comment by scootermorris** [comment]
Do we currently have a way to return a RootNetwork in our REST API?  I don't think we have a command approach to do it.

**Comment by dotasek** [comment]
Yes, that would be *GET /v1/collections *

It returns an array of SUIDs.

**Comment by bdemchak** [comment]
I think Scooter is asking about returning the nodes and edges in the root network, not the list of subnetwork SUIDs. CX does this very nicely, and pretty much along the lines of what you're thinking. The CX document is getting old, but the most authoratative I know is here: https://docs.google.com/document/d/1kAUzVj6X86YCWHnTyZtybh1lt4zO-M6anCMJBD_PyG0/edit#heading=h.czluozfc8nwp

I'm not so much advocating that anyone actually read this document, but there is a useful Aspects inventory on page 5 ... it's a picture that shows the fields in each aspect and how aspects relate to each other.

I'm not suggesting that we actually exchange CX for the CyREST result, but it's far from a crazy idea. The alternative would be to cook up yet another transmission format that isn't as comprehensive. 

The resolution to this question wouldn't be in the aesthetics of the stream, but in what it can contain and how the receiver would be able to parse it. If that's the real criteria, CX aspects are starting to look good.

**Comment by dotasek** [comment]
All models in Cytoscape 3.6 represent the new standard. Any additional models to be added should henceforth be their own issue.
