### ISSUE TITLE
tagging current version of r2cytoscape

### ISSUE THREAD

**Issue by shraddhapai** [cytoscape/cytoscape-automation#23]
We're using r2cytoscape as a dependency for our netDx (patient classifier algorithm, has an R package). It would be great to have users download a specific release of this package when installing netDx.

Is it possible to tag a version of the cytoscape-automation repo or barring that, have r2cytoscape in its own repo, so a freeze is possible just for that?

Not sure if this constitutes a personal support question - if so I'm happy to write to cytoscape-helpdesk.
Thanks,
Shraddha

**Comment by AlexanderPico** [comment]
Moved to its own repo: https://github.com/cytoscape/r2cytoscape

Made major updates recently. Preparing to submit to bioconductor...
