### ISSUE TITLE
Need to set context in preamble paragraph

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/cytoscape-automation#3]
Every page needs to start with what we're trying to achieve for the sake of the reader. For example, to set up a Swagger entry, the annotations need to tell the reader enough to understand what the function does, what parameters/results, and how to call it. With this, the reader experiences minimal drag (maximum productivity) getting a job done.

**Comment by dotasek** [comment]
Added pre-amble to all current pages. Any requests for changes should now be made as separate issues.
