### ISSUE TITLE
Refactor py2cytoscape and r2cytoscape to use POST versions of commands

### ISSUE THREAD

**Issue by dotasek** [cytoscape/cytoscape-automation#30]
With the release of Cytoscape 3.6, commands can be accessed via POST. Making the python and R libraries use POST would provide a fix for #18 and the fairly regular occurrence of users running out of room in the GET URL.

**Comment by AlexanderPico** [comment]
r2cytoscape updated to use POST for all functions with potentially long URLs.  See new repo in preparation for bioconductor submission: https://github.com/cytoscape/r2cytoscape
