### ISSUE TITLE
Add info on Docker

### ISSUE THREAD

**Issue by dotasek** [cytoscape/cytoscape-automation#39]
@keiono originally created a great deal of documentation for executing Cytoscape workflows with Docker, and none of that seems to be represented here.

@AlexanderPico @bdemchak : should Docker have a place in this repo? Although it might slow down novice users, I think it could be great for some advanced ones. It could live in the wiki, and possibly a 'docker' script directory.

**Comment by AlexanderPico** [comment]
https://hub.docker.com/u/cytoscape/
