### ISSUE TITLE
Add info on Cloud computing

### ISSUE THREAD

**Issue by dotasek** [cytoscape/cytoscape-automation#40]
Kei had an overview of running workflows on remote servers, which might be useful to some automation scripters:

https://github.com/cytoscape/cyREST/wiki/Running-your-workflow-in-the-clouds

**Comment by bdemchak** [comment]
Let’s watch it with this … there are real issues here. I don’t mind keeping this, but real context needs to be given.

 

For example, *not* a service for the general public or even for more than one instance of a client at a time.

 

Also, if Cytoscape asks for input, there’s no way to recover.
