### ISSUE TITLE
CIResponse text references CIError ... is there a CIError anymore?

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/cytoscape-automation#5]
In https://github.com/cytoscape/cytoscape-automation/wiki/App-Developers:-App-Best-Practices#ciresponse, text references CIError ... does this structure actually exist? If so, we need material on it. If not, we can expunge it.

**Comment by dotasek** [comment]
It does exist, and is documented further down in that section. A Java snippet of the current implementation could be helpful. In the Cytoscape 3.6 API, there's an implementation in the CI Bundle, and there's also the standalone dependency they can include right now.

**Comment by dotasek** [comment]
Covered by https://github.com/cytoscape/cytoscape-automation/wiki/App-Developers:-Cytoscape-Function-Best-Practices#ciresponse-errors
