### ISSUE TITLE
Problem with rWikiPathways and RCy3 protocol in Binder

### ISSUE THREAD

**Issue by khanspers** [cytoscape/cytoscape-automation#50]
Can’t get past this command:

commandsRun(paste0('wikipathways import-as-pathway id=',human.gbm.wpids[1])) 

which produces this error:

Error in commandsGET(cmd.string, base.url) 

Running the same Rmd in standalone RStudio works fine. 

https://github.com/cytoscape/cytoscape-automation/blob/master/for-scripters/R/notebooks/rWikiPathways-and-RCy3.Rmd

**Comment by AlexanderPico** [comment]
Here also, it would help to distinguish between memory limit vs buggy command. @khanspers Can you run this command alone at the very beginning of a Binder session, e.g., with a specific WPID?

**Comment by khanspers** [comment]
OK, tried opening Sandbox before running anything else. It fails:

> commandsRun(paste0('wikipathways import-as-pathway id=WP4'))
RCy3::commandsGET, HTTP Error Code: 404
 url=http://localhost:1234/v1/commands/wikipathways/import-as-pathway?id=WP4
Error in commandsGET(cmd.string, base.url) :

**Comment by AlexanderPico** [comment]
Ah! Is the WikiPathways app installed? Would need to first run install.app("WikiPathways") and maybe check a few functions.

**Comment by khanspers** [comment]
That was it! Duh. But its weird because I originally ran all previous commands which include installing WP app...... Closing.

**Comment by AlexanderPico** [comment]
Right. So this confirms the test that the function runs fine, but this is still an open bug that might be due to memory capacity or something other than this function. The overall noteboook still fails, right?

**Comment by khanspers** [comment]
Actually, I just fixed a typo in the Rmd that made the code to install the WP app look commented out. I think that was the problem. That line was fine in Kozo's other WP Rmd, so I was thinking I had installed in this Rmd too. Once its installed everything runs as expected, until openSession(), which is a known bug. So I can't test the rest as-is.
