### ISSUE TITLE
Replacement for using py2cytoscape.data?

### ISSUE THREAD

**Issue by JamesPino** [cytoscape/cytoscape-automation#56]
I see a deprecation warning for using any of the entries to py2cytoscape.data. Are there any examples of doing the same type of function calls without it? I have started to use the cyclient api directly, but there are some things that don't seem to translate. For example, passing a networkX DiGraph to create a network or lack of batch updates for setting properties to nodes (seems to do them individually now which takes a long time for 10k nodes). I like the cyrest api a lot more, I just can't seem to find examples for the same type of modules that I am building so have to create them manually.

**Comment by AlexanderPico** [comment]
As far as I'm aware, py2cytoscape is no longer supported. Current development is focused on py4cytoscape (https://github.com/bdemchak/py4cytoscape). We are in the middle of updating documentation, tutorials, links, etc, as the package is finalized.

**Comment by JamesPino** [comment]
Thanks! Any estimate for when py4cytoscape will be finalized?

**Comment by AlexanderPico** [comment]
It's ready to go today. There is just always more to do... :)

**Comment by AlexanderPico** [comment]
It's more mature and robust than the current py2cytoscape, for example.

**Comment by bdemchak** [comment]
Hi, James –

 

I’m Barry Demchak, main author (for now) of py4cytoscape.

 

The first goal of py4cytoscape is to reach feature parity with RCy3, which includes matching function signatures and functionality. They’re almost there (mostly) and will evolve in lock step over time. The reasons are pretty simple and obvious: sharing good ideas, easing cross-language workflow porting, easing instruction, and easing documentation. 

 

A py4cytoscape bonus: it’s likely that workflows in remote Jupyter Notebooks running py4cytoscape will be able to control Cytoscape on a desktop. This will make sharing workflows much more feasible than now, and will enable a number of other nice scenarios. I don’t know whether there’s a plan for this for RCy3, but it seems to me that it could be possible.

 

Once parity is reached, we’ll be in a position to incorporate new features, including those found only in py2cytoscape. We hope to do this, but would make concrete plans only after py4cytoscape rolls out.

 

I would be very pleased to include your voice in our plans, and for you to give us feedback on py4cytoscape (as it is now), too. Users with real needs are gold!

 

Are you interested? And how could you see yourself working with us?
