### ISSUE TITLE
A Thank You To All

### ISSUE THREAD

**Issue by skilfullycurled** [cytoscape/cytoscape-automation#63]
Hi,

Sorry to fill up the issue queue but I just felt the need to say to express my gratitude to anyone who worked on this.

I'm working on a project using the pure Python implementation of [Processing](https://github.com/p5py/p5) and this opens up so many more possibilities.

Extra thanks to those who worked on the tutorials.  

They are so helpful and comprehensive.

Don't know how far I'll get but I'll be sure to pass along whatever I come up with.

Again, many thanks,

Benjamin

**Comment by AlexanderPico** [comment]
Thanks @skilfullycurled. I made sure to share this with the team. Appreciation is always appreciated :)

While you are here, is there anything we can add or fix to make Cytoscape automation work better for you? Let us know as you work with it. I presume you're using the py4cytoscape library. We are putting a lot of work into refining this. So please do share ideas and issues in that repo when you have some: https://github.com/cytoscape/py4cytoscape/issues.
