### ISSUE TITLE
In Diffusion example, create clean separation between Cytoscape Commands and Functions

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/cytoscape-automation#7]
In here: https://github.com/cytoscape/cytoscape-automation/wiki/App-Developers:-Adding-Automation-to-Existing-Apps

Half way through, I got confused as to what could be done to Commands to achieve a good Swagger document, as compared to what the precise motivation and mechanics were for adding Cytoscape Functions. If we can separate them, I think we can see how Functions really shine. 

Note, too, that I have a number of [BD] comments we should talk about.

**Comment by dotasek** [comment]
Addressed comments. Any that should persist, notably ones whose answers will change once Cytoscape 3.6 is released, are included in the markdown as empty links (functionally comments)
