### ISSUE TITLE
Traverse a cyclic graph from point A to B

### ISSUE THREAD

**Issue by brunolnetto** [cytoscape/cytoscape-automation#76]
Hi,

I am a new user of Cytoscape and have no patience to explore exhaustively the library myself. There is a well-known use case for traversing a graph from point A to point B. I am pretty sure this library comprehends the "linear" case, since the topic is broadly researched, and called depth and breadth traverse. My question refers to the case when loops appear on the original graph. In this case, the previously mentioned algorithm gets stuck on these cycles, both in directed and undirected structures. 

Since you have much more resources than myself, I propose adapting the algorithm available on [this repository](https://github.com/quivero/quivero-api/blob/ac1f50b5309c1b2bc1cca3af2e551b4c86fb3f13/data-structures/graph/Graph.js#L2198). 

The rationale is:

1. Find non-cyclic paths
2. Find cycles ([Tarjan algorithm](https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm))
3. Find the intersection between each non-cyclic path and cycle (Extended Venn/Euler algorithm: implementation [here](https://github.com/quivero/quivero-api/blob/ac1f50b5309c1b2bc1cca3af2e551b4c86fb3f13/utils/arrays/arrays.js#L507));
4. Find the intersection between cycles themselves (Extended Venn/Euler algorithm: implementation [here](https://github.com/quivero/quivero-api/blob/ac1f50b5309c1b2bc1cca3af2e551b4c86fb3f13/utils/arrays/arrays.js#L507));
5. Find in and out vertices on non-cyclic paths to cycles;
6. Find paths from out to in vertices along cycles;
6. Glue these cyclic-paths on non-cyclic paths;

I thank you for your attention.

**Comment by AlexanderPico** [comment]
Thanks. I'll share this on the Cytoscape app developer mailing list in case anyone is interested in implementing such an algorithm in Cytoscape. 

This repo is for automation use cases involving CyREST, RCy3 and py4cytoscape. I'll close this issue here since it's not relevant.
